### ISSUE TITLE
where条件解析失败

### ISSUE THREAD

**Issue by evalor** [top-think/think-orm#11]
使用Mongo驱动查询时，进行任何含有where操作都将得到一个异常

```
Undefined offset: 1 in file /vendor/topthink/think-orm/src/db/builder/Mongo.php line 216

#1 /vendor/topthink/think-orm/src/db/builder/Mongo.php(472): think\db\builder\Mongo->parseWhere(Object(think\db\Mongo), Array)
#2 /vendor/topthink/think-orm/src/db/connector/Mongo.php(1083): think\db\builder\Mongo->select(Object(think\db\Mongo))
#3 /vendor/topthink/think-orm/src/db/Query.php(2297): think\db\connector\Mongo->find(Object(think\db\Mongo))
#4 /App/Controller/Index.php(25): think\db\Query->find()
```

查询代码
```
$users = new Users;
$user  = $users->where('username', 'admin')->find();
var_dump($user);
```

**Comment by evalor** [comment]
新版本已修正
