### ISSUE TITLE
使用thinkphp6.0+thinkphp-swoole+think-orm时，连接池mysql重连失败

### ISSUE THREAD

**Issue by bellpk** [top-think/think-orm#174]
SQLSTATE[HY000]: General error: 2006 MySQL server has gone away

trace: 
#0 /project_root/vendor/topthink/think-orm/src/db/PDOConnection.php(1406): PDO->exec('SAVEPOINT trans...')
#1 /project_root/vendor/topthink/think-orm/src/db/PDOConnection.php(1372): think\\db\\PDOConnection->startTrans()
#2 /project_root/vendor/topthink/think-orm/src/db/concern/Transaction.php(82): think\\db\\PDOConnection->transaction(Object(Closure))
#3 /project_root/vendor/topthink/think-orm/src/Model.php(711): think\\db\\BaseQuery->transaction(Object(Closure))

![image](https://user-images.githubusercontent.com/12622129/89167244-bb7fe100-d5ad-11ea-925d-f7712dc0dbef.png)

由于1414行递归调startTrans()时未终止执行，导致1416行的异常仍旧抛了出来。

![image](https://user-images.githubusercontent.com/12622129/89167525-1a455a80-d5ae-11ea-93e8-34a2398c518c.png)
对比729行可以清楚看出区别。

**Comment by bellpk** [comment]
#175 startTrans没有返回值，所以应该加个else分支就行了，已提pull request，谢谢。 @liu21st

**Comment by gsons** [comment]
我的问题跟你类似 麻烦帮忙看下
```
[29-Aug-2020 16:13:36 UTC] PHP Warning:  PDOStatement::execute(): MySQL server has gone away in E:\project\vendor\topthink\think-orm\src\db\Connection.php on line 720
[29-Aug-2020 16:13:36 UTC] PHP Stack trace:
[29-Aug-2020 16:13:36 UTC] PHP   1. Gsons\project\PageItem->run() E:\project\src\project\PageItem.php:0
[29-Aug-2020 16:13:36 UTC] PHP   2. think\db\Query->insert() E:\project\src\project\PageItem.php:120
[29-Aug-2020 16:13:36 UTC] PHP   3. think\db\connector\Mysql->insert() E:\project\vendor\topthink\think-orm\src\db\Query.php:2696
[29-Aug-2020 16:13:37 UTC] PHP   4. think\db\connector\Mysql->execute() E:\project\vendor\topthink\think-orm\src\db\Connection.php:951
[29-Aug-2020 16:13:37 UTC] PHP   5. PDOStatement->execute() E:\project\vendor\topthink\think-orm\src\db\Connection.php:720
```
