### ISSUE TITLE
当我第一次使用composer安装think-orm时，弹出无法找到builder对象

### ISSUE THREAD

**Issue by captainstdin** [top-think/think-orm#306]
![image](https://user-images.githubusercontent.com/56504552/139588966-aded478c-18cd-4b1a-b553-cdd06bde7138.png)

`Error: Class '\think\db\builder\' not found in /Users/admin/Documents/phpstormProjects/webmancms/vendor/topthink/think-orm/src/db/Connection.php:128
Stack trace:
#0 /Users/admin/Documents/phpstormProjects/webmancms/vendor/topthink/think-orm/src/DbManager.php(272): think\db\Connection->__construct(Array)
#1 /Users/admin/Documents/phpstormProjects/webmancms/vendor/topthink/think-orm/src/DbManager.php(233): think\DbManager->createConnection('mysql')
#2 /Users/admin/Documents/phpstormProjects/webmancms/vendor/topthink/think-orm/src/DbManager.php(216): think\DbManager->instance('mysql', false)
#3 /Users/admin/Documents/phpstormProjects/webmancms/vendor/topthink/think-orm/src/DbManager.php(374): think\DbManager->connect()
#4 [internal function]: think\DbManager->__call('query', Array)
#5 /Users/admin/Documents/phpstormProjects/webmancms/vendor/topthink/think-container/src/Facade.php(96): call_user_func_array(Array, Array)
`

**Comment by captainstdin** [comment]
错误的多了一个 配置 "drive"=>'mysqll' 去掉就好了
