### ISSUE TITLE
写入大量数据行时报错！

### ISSUE THREAD

**Issue by xiasf** [top-think/think-orm#57]
```
Db::table('t_company_info2')->insertAll($data);
```

```
此文件有: 117 条数据
正在写入数据...
写入成功！

此文件有: 4999 条数据
正在写入数据...                

Fatal error: Uncaught think\db\exception\PDOException: SQLSTATE[HY000]: General error:  1390 Prepared statement contains too many placeholders in D:\wamp64\www\ex\vendor\top think\think-orm\src\db\Connection.php:737
Stack trace:
 #0 D:\wamp64\www\ex\vendor\topthink\think-orm\src\db\Connection.php(1036): think\db\Co nnection->execute('INSERT INTO `t_...', Array, Object(think\db\Query))
#1 D:\wamp64\www\ex\vendor\topthink\think-orm\src\db\Query.php(2724): think\db\Connect ion->insertAll(Object(think\db\Query), Array, false, NULL)
#2 D:\wamp64\www\ex\index.php(172): think\db\Query->insertAll(Array)
#3 D:\wamp64\www\ex\index.php(159): insert(Array)
#4 D:\wamp64\www\ex\index.php(175): read_all('./file_path')
#5 {main}
thrown in D:\wamp64\www\ex\vendor\topthink\think-orm\src\db\Connection.php on line 7 37
--
```

**Comment by liu21st** [comment]
insertall方法大量数据的时候尽量配合limit方法
